# Generated by Django 2.0.1 on 2018-01-30 19:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0002_auto_20180130_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
