# Generated by Django 2.0.1 on 2018-01-31 17:50

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0007_auto_20180131_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Elected offices held and civic involvement'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(help_text="Automatically generated slug. Don't recommend changing!"),
        ),
        migrations.AlterField(
            model_name='election',
            name='slug',
            field=models.SlugField(help_text="Automatically generated slug. Don't recommend changing!", unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='slug',
            field=models.SlugField(help_text="Automatically generated slug. Don't recommend changing!"),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
