# Generated by Django 2.0.1 on 2018-01-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0008_auto_20180131_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
