# Generated by Django 2.0.1 on 2018-01-30 18:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('is_incumbent', models.BooleanField()),
                ('party', models.CharField(choices=[('GOP', 'Republican'), ('DEM', 'Democrat')], max_length=3)),
                ('website', models.URLField(blank=True, help_text="The url for the candidate's website.")),
                ('facebook', models.URLField(blank=True, help_text="The url for the candidate's Facebook.")),
                ('twitter', models.URLField(blank=True, help_text="The url for the candidate's Twitter.")),
                ('responses', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(verbose_name='election date')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qas.Election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qas.Race'),
        ),
    ]
