# Generated by Django 2.0.1 on 2018-01-30 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0003_race_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], size=4),
            preserve_default=False,
        ),
    ]
