# Generated by Django 2.0.1 on 2018-01-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0004_auto_20180130_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qas.Race'),
        ),
    ]
