# Generated by Django 2.0.1 on 2018-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0006_auto_20180130_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Elected offices held and civic involvement'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='occupation',
            field=models.TextField(blank=True),
        ),
    ]
