# Generated by Django 2.0.1 on 2018-02-06 21:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0011_auto_20180202_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='faq_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='FAQ text goes here'),
        ),
    ]
