# Generated by Django 2.0.1 on 2018-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0012_election_faq_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
