# Generated by Django 2.0.1 on 2018-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0013_race_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='special_status',
            field=models.TextField(blank=True),
        ),
    ]
