# Generated by Django 2.0.1 on 2018-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas', '0014_auto_20180221_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='special_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
